# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JodCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JodCard
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'JodCard-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JodCardTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


